version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.4
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    networks:
      - elk
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    ports:
      - "5601:5601"
    networks:
      - elk
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.4
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log/fastapi:/var/log/fastapi
    networks:
      - elk
    restart: unless-stopped

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"  # FastAPI напрямую доступен на 8000 порту
    volumes:
      - /var/log/fastapi:/var/log/fastapi
    networks:
      - elk
    restart: unless-stopped

networks:
  elk:
    driver: bridge

volumes:
  es_data: