filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/fastapi/app.log
  fields:
    app: fastapi
    environment: development
  fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~